### PR TITLE
chore(package): pinned dependencies

### PR DESCRIPTION
**Pull request by emig**
pin material_ui to 0.12.4

fixes build error

### CODE REVIEW

**Comment by emig** [comment]
so I get this now:

```
semantic-release ERR! pre This test run was triggered by a pull request and therefore a new version won’t be published.
```

seems reasonable since it is a PR.

**Comment by emig** [comment]
so I get this now:

```
semantic-release ERR! pre This test run was triggered by a pull request and therefore a new version won’t be published.
```

seems reasonable since it is a PR.

**Comment by emig** [comment]
so I get this now:

```
semantic-release ERR! pre This test run was triggered by a pull request and therefore a new version won’t be published.
```

seems reasonable since it is a PR.

**Comment by gr2m** [comment]
> semantic-release ERR! pre This test run was triggered by a pull request and therefore a new version won’t be published.

yes that’s by design

**Comment by tthew** [comment]
LGTM. Thanks!

**Pull request merged**
